org: geraldocolchado
service: api-cursos

provider:
  name: aws
  runtime: python3.13
  memorySize: 512
  timeout: 30
  iam:
    role: arn:aws:iam::520501359331:role/LabRole

functions:
  buscar:
    handler: BuscarCurso.lambda_handler
    events:
      - http:
          path: /cursos/buscar
          method: post
          cors: true
          integration: lambda
  listar:
    handler: ListarCursos.lambda_handler
    events:
      - http:
          path: /cursos/listar
          method: get
          cors: true
          integration: lambda
  crear:
    handler: CrearCurso.lambda_handler
    events:
      - http:
          path: /cursos/crear
          method: post
          cors: true
          integration: lambda
